[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=23.0.0",
    "aiohttp>=3.9.0",
    "better-profanity>=0.7.0",
    "fastapi>=0.100.0",
    "gradio>=4.0.0",
    "numpy<2",
    "opencv-python-headless>=4.5.0",
    "pillow>=9.0.0",
    "python-multipart>=0.0.6",
    "python-telegram-bot==20.7",
    "tensorflow>=2.8.0,<2.16.0",
    "tensorflow-hub>=0.12.0",
    "uvicorn>=0.23.0",
]
